### ISSUE TITLE
Add feature to decrypt encrypted Mogg Files.

### ISSUE THREAD

**Issue by minipicc95** [mtolly/onyx#232]
Rock Band 1 and newer games cannot play audio due to mogg file encryption. Can you please a way to decrypt the mogg files so I can hear the real audio?

**Comment by mcjojo3** [comment]
This ^

I keep getting: `ERROR! moggToOgg: encrypted MOGG (type 0xD) not supported`

**Comment by AARP41298** [comment]
check #184

but there is a patcher version of c3

**Comment by mtolly** [comment]
Onyx now supports typical RB encrypted MOGGs in version `20240719`
