### ISSUE TITLE
Converting 5 lane GH drums charts to RB creates a 4 lane legacy drums chart, not a pro drums chart

### ISSUE THREAD

**Issue by GeeForce11** [mtolly/onyx#241]
Converting 5 lane GH drum charts to RB3CON all notes get marked as toms creating a 4 lane legacy drums chart and not a pro drums chart. For example during play Phase Shift converts on the fly the 5 lane GH drums chart to 4 lane RB pro drums assigning the 5 lane Green note to 4 lane GreenTom, 5 lane Orange note to 4 lane GreenCymbal, 5 lane Orange/Green note combo to 4 lane GreenCymbal/GreenTom combo (4 lane BlueCymbal/GreenTom combo or BlueTom/GreenCymbal combo would be better), 5 lane Kick note is 4 lane Kick, 5 lane Red note in 4 lane Red, 5 lane Yellow note is 4 lane YellowCymbal, 5 lane Blue note is 4 lane BlueTom. Suggesting that something like this should be implemented in Onyx converter.

**Comment by mtolly** [comment]
This is implemented in the new build `20230917`
