### ISSUE TITLE
yarg support

### ISSUE THREAD

**Issue by binarygeek119** [mtolly/onyx#245]
is a new rock band clone game with vocals.
your tool my need to be adjected for this game im unsure.

https://github.com/YARC-Official/YARG

there also fret smasher a guitar hero clone

**Comment by JamesIsWack** [comment]
> is a new rock band clone game with vocals. your tool my need to be adjected for this game im unsure.
> 
> https://github.com/YARC-Official/YARG
> 
> there also fret smasher a guitar hero clone

YARG supports Clone Hero songs directly. theres no need to use onyxite.

**Comment by mtolly** [comment]
Closing as yes, YARG reads CH format songs (either folder or .sng) and Onyx created files should work as is, but please add bugs if there are specific issues.
