### ISSUE TITLE
(Regression) Spanish song names

### ISSUE THREAD

**Issue by AARP41298** [mtolly/onyx#270]
First of all, thank you so much for the MOGG feature, one less step when creating packs.
But the
`Fix RB Quick Convert to encode all pack songs.dta files as Latin-1 for consistency` brokes the accents.

Left, ss of an old gameplay.
Right, a fresh pack.
![image](https://github.com/user-attachments/assets/2df55197-8290-4752-aeaf-308c342a4ddb)

Manual fix:
replace
('encoding' 'latin1') -> ('encoding' 'utf8')
But this will only left a blank space in the name, now i have to fix all the �
Man� -> Maná
//Me Gustas T� -> Me Gustas Tú
![image](https://github.com/user-attachments/assets/4c4a2b45-fd82-4a25-ba4e-b138ba438a08)

Maybe leave the latin1 encoding, but dont touch the accent, my paks are organized, and i would only need to use replace in 1 or 2 song.dta
![image](https://github.com/user-attachments/assets/f7ef984b-46e4-4764-9b3a-aa872342b586)

**Comment by mtolly** [comment]
Hi, thank you for the report. I am not able to replicate this problem directly; I downloaded the "Me Gustas Tú" custom song, placed it in a pack, and it seems to be correctly converted from UTF-8 to Latin-1.

Could you maybe upload a file you started from, one with an accented character that you gave to Quick Convert that produced the bad pack? I am not sure but I think maybe the input file had a different encoding from what it claimed, like it was Latin-1 but claimed to be UTF-8, or vice versa. I can probably handle this case and have it fix the encoding either way, but I'd like to try and see the problem happen so I can be sure it is handled right.

The reason I changed packs to have a consistent encoding is because a combined `songs.dta` with 2 differently encoded song data is difficult to edit - text editors will either read it incorrectly or save it with a single encoding. If it's not possible to do right then I can disable it or make it optional, but I'd like to first try to have it work correctly.

**Comment by mtolly** [comment]
(Saving notes for myself)
Based on the characters shown, my best guess at the issue is

- Non-ASCII characters got replaced with the Unicode replacement character `�` (this could happen via [`decodeUtf8 lenientDecode`](https://hackage.haskell.org/package/text-2.1.1/docs/Data-Text-Encoding-Error.html#v:lenientDecode) which is used [here](https://github.com/mtolly/onyx/blob/fbbacd227a19eccc8d35340d4b1ac47eb481615b/haskell/packages/onyx-lib/src/Onyx/QuickConvert/RockBand.hs#L1145)?)
- `�` encoded as UTF-8 is `EF BF BD`
- Those bytes interpreted as Latin-1 are `ï¿½`, except RB3 doesn't have a glyph for `½` so it's just `ï¿`

I don't understand how that would happen though, because if we started by trying to decode UTF-8, we would be encoding as Latin-1, not UTF-8 again, and `�` would just become `?`.

Another similar option is it's somehow the UTF-8 Byte Order Marker, which would be `EF BB BF` or `ï»¿` as Latin-1 (RB3 also has no glyph for `»`). But that seems less likely, not sure how that would end up replacing these characters.

**Comment by AARP41298** [comment]
Thank you for the response. I test only the "Me Gustas Tú" song with 
`Load a song->RB3->Create PS3 PKG file` and the result is the same.
I use RPCS3, installing the pkg by dragging the file to the window.

Custom songs:
[Me gustas tú](https://rhythmverse.co/songfile/5e5517110b5076.54121838)
[Ángeles Fuimos](https://rhythmverse.co/songfile/a37a53cacccc4f97a963a8fdf3e82167)
![image](https://github.com/user-attachments/assets/c99d5e09-7f70-4758-acb1-f0e36efbae2a)
![image](https://github.com/user-attachments/assets/f7cbdc03-b5e2-4ac8-90ed-5c5758427f3d)

[songs.txt](https://github.com/user-attachments/files/16475204/songs.txt)

**Comment by mtolly** [comment]
Hmm... I tried doing exactly that, with RPCS3 on Windows, and I am still unable to get the bug.

![Screenshot 2024-08-02 221427](https://github.com/user-attachments/assets/10dcc314-9b9b-4eaf-a517-8bbd5735e044)

* [This is the pack I created](https://onyxite.org/tmp/onyx-latin-1.pkg), if you install that is it bugged in game?
* Can you upload the pack you made to somewhere?
* I'm assuming before seeing the bug, you didn't modify any `songs.dta` manually (either the input songs or the pack)? The two songs were the exact files downloaded from Rhythmverse?

**Comment by AARP41298** [comment]
Demn...
I install directly the pack you provide, and open the game inmediatly.
![image](https://github.com/user-attachments/assets/9f66b323-7490-4bab-9868-c4f693b6f2c2)

[My pack](https://www.mediafire.com/file/ke1ndqm3e462w9h/testing.pkg/file)
Yes, i didn't modify any songs.dta manually
Yes, the songs are exact files of Rhytmverse

Maybe a region issue, like excel, `$1.000,00` instead of `$1,000.00` idk :,v

Mjm...
![image](https://github.com/user-attachments/assets/b085ddb1-393e-48ed-b2b3-6bd5784619c1)

**Comment by mtolly** [comment]
Yeah I'm at a loss then, I installed your pack and it shows up correctly...
In that case I'll get a build up quick (should be this week) with options to control the RB3 encoding for both recompile and pack creation.
Hopefully that will work for now, sorry for the inconvenience! And thank you again for the help trying to track it down.

**Comment by AARP41298** [comment]
Deleted my anime and spanish packs.
Created a new pak with 5 accented songs.
![image](https://github.com/user-attachments/assets/8474dd61-6388-4c9e-9487-40bd794efba8)
Now its working...
![image](https://github.com/user-attachments/assets/744ff1bd-80fd-48ce-abae-c17b9e61488e)

Trying again with all the songs

**Comment by AARP41298** [comment]
I found the problem.

I always replace the game_origin to sort my packs. Ex. spanish
When i was testing only "Me Gustas Tú" i think i forgot to delete the broken spanish pack, im so sorry about that, my bad.

Using replace in notepad works good.
But opening the file with vscode is the problem, after juggling a bit, i found this.

![image](https://github.com/user-attachments/assets/98c00d71-7bc2-4a3f-b761-90965e94b618)
![image](https://github.com/user-attachments/assets/c573aede-8661-4d83-bc09-4f62ff25e54e)
"Western" is the suggestion for the anime pack. Replaced the game_origin and works like allways.

For the record, the suggestion in the spanish pack is
![image](https://github.com/user-attachments/assets/fb0d4940-24bb-4ef6-b346-eedab433f819)
And "breaks" again the accents.
![image](https://github.com/user-attachments/assets/bc23ddea-536e-4cac-a653-84c4fc1763b7)

Again, im so sorry for not cleaning properly the already installed.

**Comment by AARP41298** [comment]
Hi, its me again
Thank you for the folder option, another less step to add custom song.
I think i found a kind of solution.

The main problem is: the songs has a mix of encodings, this wouldnt be a problem if  the `encoding` param is correctly seted.

<details><summary>EX: arsénico uses `é`, BUT has `latin1`</summary>
<p>

![00 arsenico dta](https://github.com/user-attachments/assets/0844d576-2714-46c8-bdbe-a7e11b0cb778)

</p>
</details> 
<details><summary>I can manually open vs code and set `utf8`</summary>
<p>

![image](https://github.com/user-attachments/assets/7bb31e07-9378-4955-bbcd-117e49e912f1)

</p>
</details> 

<details><summary>And it is fixed, right?</summary>
<p>

![image](https://github.com/user-attachments/assets/5fe754d7-7e22-4c9d-8a52-95e95293d2eb)

</p>
</details> 


Wrong :,v
vscode would save the entire `song.dta`, "damaging" in the process the "perfectly" latin-1 characters.

<details><summary>"El triste" BEFORE entire save</summary>
<p>

![03 triste dta](https://github.com/user-attachments/assets/64b67dc6-d9b3-46ad-a83c-24f623600c72)
![04 triste select](https://github.com/user-attachments/assets/e9494c76-4d88-4def-8648-986df6e7f6a9)
</p>
</details>

<details><summary>"El triste" AFTER entire save</summary>
<p>

Aparently nothing wrong
![image](https://github.com/user-attachments/assets/3a5aad88-600b-42d9-9485-01ef4af9b6f7)

BUT ingame
![image](https://github.com/user-attachments/assets/ec79ff90-a465-4889-89a4-aa6d06eea452)

</p>
</details> 


<details><summary>EVIDENCE TESTING LATIN 1 AND UTF8 OPTIONS IN ONYX</summary>
<p>

<details><summary>Onyx latin1</summary>
<p>

![06 onyx](https://github.com/user-attachments/assets/424cb0ba-b0e0-406a-9eaa-7abd9d65ac0e)

</p>
</details> 


<details><summary>Arsénico select</summary>
<p>

![01 arsenico select](https://github.com/user-attachments/assets/03e1d3cd-167f-4a84-ae50-a688ab989802)

</p>
</details> 

<details><summary>Arsénico lyrics</summary>
<p>

![02 arsenico letra](https://github.com/user-attachments/assets/0cda912c-3ccb-4172-a190-f975b430de64)

</p>
</details> 
 

<details><summary>El triste lyrics</summary>
<p>

![05 triste lyrics](https://github.com/user-attachments/assets/fd180884-9509-4ea1-b807-c0628eec2136)

</p>
</details> 


<details><summary>Onyx utf8</summary>
<p>

![07 onyx](https://github.com/user-attachments/assets/6777d1f3-b81d-41ce-88e1-247dfbf5a496)

</p>
</details> 

<details><summary>Onyx log utf8</summary>
<p>

![08 onyx log utf8](https://github.com/user-attachments/assets/ad686042-c06c-4814-bbf9-d825e48c987f)

</p>
</details> 
<details><summary>Arsénico select</summary>
<p>

![09 arsenico select utf8](https://github.com/user-attachments/assets/8f001a9d-a32e-4df7-ac87-40712c9a46c5)

</p>
</details> 
<details><summary>Arsénico lyrics</summary>
<p>

![10 arsenico lyrics utf8](https://github.com/user-attachments/assets/0fdeeae6-0be0-4739-a269-e4814f87f809)

</p>
</details> 
<details><summary>El triste select</summary>
<p>

![10 triste select utf8](https://github.com/user-attachments/assets/296dc497-9b8b-42c7-b349-343cb8cd1c71)

</p>
</details> 


</p>
</details> 

A quick chat with gpt give me the answer

```python

import re

def fix_encoding(input_file, output_file):
    # Leer el archivo en modo binario para trabajar con los bytes directamente
    with open(input_file, 'rb') as f:
        content = f.read()

    # Decodificar el contenido
    try:
        fixed_content = content.decode('utf-8').encode('latin1').decode('utf-8')
    except UnicodeDecodeError:
        fixed_content = content.decode('latin1')

    # Corregir las vocales con acento mal codificadas
    replacements = {
        "Ã¡": "á", "Ã©": "é", "Ã­": "í", "Ã³": "ó", "Ãº": "ú",
        "Ã": "Á", "Ã‰": "É", "Ã": "Í", "Ã“": "Ó", "Ãš": "Ú",
        "Ã±": "ñ", "Ã‘": "Ñ", "Ã¼": "ü", "Ãœ": "Ü"
    }
    for broken, correct in replacements.items():
        fixed_content = fixed_content.replace(broken, correct)

    # Reemplazar 'encoding' 'latin1' por 'encoding' 'utf8'
    fixed_content = re.sub(r"\('encoding' 'latin1'\)", "('encoding' 'utf8')", fixed_content)

    # Guardar el archivo corregido
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(fixed_content)

    print(f"Archivo corregido guardado en: {output_file}")

 # Ejemplo de uso
fix_encoding('songs.dta', 'songs.dta.fix')

```

<details><summary>Arsénico AFTER fix</summary>
<p>

![image](https://github.com/user-attachments/assets/cb770507-9454-4ebb-93bb-974b184f80ec)
![11 arsenico fix](https://github.com/user-attachments/assets/f0a63f3d-239e-46b1-8c9e-a1f87a3085a8)

</p>
</details> 
<details><summary>El triste AFTER fix</summary>
<p>

![12 triste fix](https://github.com/user-attachments/assets/49c5e409-4b68-49af-a0f7-a6afddb863d3)
![image](https://github.com/user-attachments/assets/39c2075f-e2dd-49b1-9b9d-b4140ada56b9)


</p>
</details> 

Now, i can open it with vscode as usual, and replace `game_origin` as i used to, letting me show only my custom game source
![image](https://github.com/user-attachments/assets/2958b388-a2d7-4284-b227-ba03f7868ffc)

![image](https://github.com/user-attachments/assets/6d859d58-213f-4b52-800c-50e5159d5bd8)
